apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventhive-backend
  namespace: default
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: eventhive-backend
  template:
    metadata:
      labels:
        app: eventhive-backend
    spec:
      containers:
      - name: eventhive-backend
        image: 7arj/eventhive-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://host.docker.internal:27017/eventhive" 
        - name: PORT
          value: "5000"
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"