name: EventHive CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Quality Checks (Lint & Test)
  quality-check:
    name: Lint & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Run Linting
        run: npm run lint

      - name: Run Unit Tests
        run: npm test

  #  Build, Scan & Push 
  build-and-push:
    name: Docker Build & Scan
    runs-on: ubuntu-latest
    needs: quality-check  
    if: github.ref == 'refs/heads/main' # Only push on main branch
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

     # login to Docker Hub using Secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #  Build the Docker Image 
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/eventhive-backend:${{ github.sha }} ./backend

      #  Security Scan (Trivy)  
      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/eventhive-backend:${{ github.sha }}'
          format: 'table'
          exit-code: '1'          # Fail pipeline if severe issues found
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      # Push to Docker Hub (Only if Scan Passed)
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/eventhive-backend:${{ github.sha }}
          # Also tag as 'latest' for convenience
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/eventhive-backend:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/eventhive-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/eventhive-backend:latest
  
  #  Continuous Deployment (CD)
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Create a real Kubernetes cluster inside the GitHub Runner
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
        with:
          version: v0.20.0

      # 2. Check the cluster status (Verification)
      - name: Verify Cluster Info
        run: |
          kubectl cluster-info
          kubectl get nodes

      
      - name: Deploy Manifests
        run: |
          kubectl apply -f backend/k8s/deployment.yaml
          kubectl apply -f backend/k8s/service.yaml
          echo " Successfully deployed to Ephemeral Cluster"